/**
 * Curriculum seed script for Golden Generation Web Dev Course.
 * Run with: npx tsx supabase/seed_gg_curriculum.ts
 * Requires: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars.
 */
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://zwwhsdtmlyvvzhfbaegr.supabase.co",
  "sb_publishable_mIPsMnaHDmKfahHqf2dN9A_f40q4unY",
);
// const supabase = createClient(
//   process.env.NEXT_PUBLIC_SUPABASE_URL!,
//   process.env.SUPABASE_SERVICE_ROLE_KEY!,
// );

type Item = {
  phase: number;
  week: number;
  day?: number;
  title: string;
  topic_type: "video" | "exercise" | "quiz" | "project" | "review" | "setup";
  estimated_minutes?: number;
};

const curriculum: Item[] = [
  // ── PHASE 0: Introduction & Fundamentals (Weeks 1–2) ──────────────────────
  {
    phase: 0,
    week: 1,
    day: 1,
    title: "Watch: Course Introduction - Roadmap (11:26)",
    topic_type: "video",
    estimated_minutes: 12,
  },
  {
    phase: 0,
    week: 1,
    day: 1,
    title: "Watch: Meet your Instructor (5:26)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 0,
    week: 1,
    day: 1,
    title: "Setup: Install required tools",
    topic_type: "setup",
    estimated_minutes: 60,
  },
  {
    phase: 0,
    week: 1,
    day: 2,
    title: "Watch: Lets talk about AI hype (6:11)",
    topic_type: "video",
    estimated_minutes: 7,
  },
  {
    phase: 0,
    week: 1,
    day: 2,
    title: "Watch: How does the internet work (8:42)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 0,
    week: 1,
    day: 2,
    title: "Watch: A big picture of web application (4:50)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 0,
    week: 1,
    day: 2,
    title: "Practice: Create mind map of internet structure",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 0,
    week: 1,
    day: 3,
    title: "Watch: What tools you need for web development (9:50)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 0,
    week: 1,
    day: 3,
    title: "Watch: How to setup your code editor (18:04)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 0,
    week: 1,
    day: 3,
    title: "Hands-On: Download, install, and configure VSCode",
    topic_type: "setup",
    estimated_minutes: 60,
  },
  {
    phase: 0,
    week: 1,
    day: 4,
    title: "Watch: Jobs salary range and skills (10:21)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 0,
    week: 1,
    day: 4,
    title: "Watch: Frontend backend and APIs (9:10)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 0,
    week: 1,
    day: 4,
    title: "Reflection: Identify and document your learning goals",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 0,
    week: 1,
    day: 5,
    title: "Review notes from all days this week",
    topic_type: "review",
    estimated_minutes: 30,
  },
  {
    phase: 0,
    week: 1,
    day: 5,
    title: "Complete setup verification checklist",
    topic_type: "exercise",
    estimated_minutes: 30,
  },

  {
    phase: 0,
    week: 2,
    day: 1,
    title:
      "Watch: How to setup your code editor (review + advanced tips) (18:04)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 0,
    week: 2,
    day: 1,
    title: "Hands-On: Configure Emmet, snippets, extensions",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 0,
    week: 2,
    day: 2,
    title: "Watch: Introduction to GIT series (5:51)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 0,
    week: 2,
    day: 2,
    title: "Watch: Git init and hidden folder (17:30)",
    topic_type: "video",
    estimated_minutes: 18,
  },
  {
    phase: 0,
    week: 2,
    day: 2,
    title: "Hands-On: Initialize first Git repository",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 0,
    week: 2,
    day: 3,
    title: "Watch: Git commits and logs (16:31)",
    topic_type: "video",
    estimated_minutes: 17,
  },
  {
    phase: 0,
    week: 2,
    day: 3,
    title: "Hands-On: Create 10+ commits with meaningful messages",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 0,
    week: 2,
    day: 4,
    title: "Watch: Insight of pushing code to GitHub (first 15 mins)",
    topic_type: "video",
    estimated_minutes: 15,
  },
  {
    phase: 0,
    week: 2,
    day: 4,
    title: "Hands-On: Create GitHub account and push repository",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 0,
    week: 2,
    day: 5,
    title: "Quiz: Phase 0 Completion Quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },
  {
    phase: 0,
    week: 2,
    day: 5,
    title: "Review: All concepts from weeks 1–2",
    topic_type: "review",
    estimated_minutes: 30,
  },

  // ── PHASE 1: HTML Foundations (Weeks 3–4) ─────────────────────────────────
  {
    phase: 1,
    week: 3,
    day: 1,
    title: "Watch: What is HTML (12:50)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 1,
    week: 3,
    day: 1,
    title: "Watch: Emmet, headings and block vs inline (29:49)",
    topic_type: "video",
    estimated_minutes: 30,
  },
  {
    phase: 1,
    week: 3,
    day: 1,
    title: "Exercise: Create a Simple Heading",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 3,
    day: 1,
    title: "Exercise: Create a Paragraph with a Link",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 3,
    day: 2,
    title: "Watch: Building a semantic HTML page (20:56)",
    topic_type: "video",
    estimated_minutes: 21,
  },
  {
    phase: 1,
    week: 3,
    day: 2,
    title: "Watch: MultiMedia and ARIA in HTML (13:38)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 1,
    week: 3,
    day: 2,
    title: "Practice: Create proper semantic page structure",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 3,
    day: 3,
    title: "Watch: Tables and forms in HTML (26:42)",
    topic_type: "video",
    estimated_minutes: 27,
  },
  {
    phase: 1,
    week: 3,
    day: 3,
    title: "Exercise: Create a Simple Table",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 3,
    day: 3,
    title: "Exercise: Create a Form with Input Fields",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 3,
    day: 3,
    title: "Exercise: Create a Form with a Dropdown Menu",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 3,
    day: 4,
    title: "Exercise: Create an Image with Alt Text",
    topic_type: "exercise",
    estimated_minutes: 15,
  },
  {
    phase: 1,
    week: 3,
    day: 4,
    title: "Exercise: Create a Hyperlink that Opens in a New Tab",
    topic_type: "exercise",
    estimated_minutes: 15,
  },
  {
    phase: 1,
    week: 3,
    day: 4,
    title: "Exercise: Create a Progress Bar",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 3,
    day: 5,
    title: "Project: HTML Mini-Project — Restaurant Homepage",
    topic_type: "project",
    estimated_minutes: 120,
  },
  {
    phase: 1,
    week: 3,
    day: 5,
    title: "Quiz: HTML Quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },

  {
    phase: 1,
    week: 4,
    day: 1,
    title: "Review: HTML concepts from Week 3",
    topic_type: "review",
    estimated_minutes: 30,
  },
  {
    phase: 1,
    week: 4,
    day: 1,
    title: "Exercise: Contact form with validation",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 4,
    day: 2,
    title: "Watch: The current state of CSS (11:38)",
    topic_type: "video",
    estimated_minutes: 12,
  },
  {
    phase: 1,
    week: 4,
    day: 2,
    title: "Watch: You can write CSS in 3 places (13:47)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 1,
    week: 4,
    day: 2,
    title: "Hands-On: Style previous HTML projects with CSS",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 4,
    day: 3,
    title: "Watch: Masterclass on CSS selectors (38:43)",
    topic_type: "video",
    estimated_minutes: 39,
  },
  {
    phase: 1,
    week: 4,
    day: 3,
    title: "Exercise: CSS selector specificity challenges",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 4,
    day: 4,
    title: "Watch: Box model, inline and block elements (10:31)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 1,
    week: 4,
    day: 4,
    title: "Exercise: Box model diagrams and spacing practice",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 4,
    day: 5,
    title: "Watch: Building a web project - Login page (26:39)",
    topic_type: "video",
    estimated_minutes: 27,
  },
  {
    phase: 1,
    week: 4,
    day: 5,
    title: "Project: Login Page Project",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 1,
    week: 4,
    day: 5,
    title: "Quiz: Phase 1 Quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },

  // ── PHASE 1 (Continued): CSS Mastery (Weeks 5–6) ─────────────────────────
  {
    phase: 1,
    week: 5,
    day: 1,
    title: "Watch: Navbar project with Pseudo element (29:59)",
    topic_type: "video",
    estimated_minutes: 30,
  },
  {
    phase: 1,
    week: 5,
    day: 1,
    title: "Watch: Twitter style navbar in CSS (14:16)",
    topic_type: "video",
    estimated_minutes: 15,
  },
  {
    phase: 1,
    week: 5,
    day: 1,
    title: "Project: Build 2 navbar styles",
    topic_type: "project",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 5,
    day: 2,
    title: "Watch: Dropdown navbars and positions (15:03)",
    topic_type: "video",
    estimated_minutes: 15,
  },
  {
    phase: 1,
    week: 5,
    day: 2,
    title: "Exercise: Create dropdown menu interactions",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 5,
    day: 3,
    title: "Watch: Flexbox Masterclass (23:54)",
    topic_type: "video",
    estimated_minutes: 24,
  },
  {
    phase: 1,
    week: 5,
    day: 3,
    title: "Exercise: Create a Responsive Flexbox Layout",
    topic_type: "exercise",
    estimated_minutes: 40,
  },
  {
    phase: 1,
    week: 5,
    day: 3,
    title: "Exercise: 5 Flexbox layout challenges",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 5,
    day: 4,
    title: "Watch: Meet grid layout in CSS (18:54)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 1,
    week: 5,
    day: 4,
    title: "Watch: Grid Masterclass (31:57)",
    topic_type: "video",
    estimated_minutes: 32,
  },
  {
    phase: 1,
    week: 5,
    day: 4,
    title: "Exercise: Create a 3x3 Grid Layout",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 1,
    week: 5,
    day: 5,
    title: "Watch: Breakpoints for mobile tablet and web (19:33)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 5,
    day: 5,
    title: "Project: Responsive design page mockup",
    topic_type: "project",
    estimated_minutes: 90,
  },

  {
    phase: 1,
    week: 6,
    day: 1,
    title: "Watch: Build a custom coming soon template (33:00)",
    topic_type: "video",
    estimated_minutes: 33,
  },
  {
    phase: 1,
    week: 6,
    day: 1,
    title: "Project: Coming soon page",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 1,
    week: 6,
    day: 2,
    title: "Watch: Hands on Bootstrap integration (18:09)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 1,
    week: 6,
    day: 2,
    title: "Project: Build page with Bootstrap",
    topic_type: "project",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 6,
    day: 3,
    title: "Exercise: Complete all CSS styling exercises",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 1,
    week: 6,
    day: 4,
    title: "Quiz: CSS Quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },
  {
    phase: 1,
    week: 6,
    day: 4,
    title: "Review: All CSS concepts",
    topic_type: "review",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 6,
    day: 5,
    title: "Project: Portfolio Website (HTML + CSS + Responsive)",
    topic_type: "project",
    estimated_minutes: 180,
  },

  // ── PHASE 1B: Tailwind CSS (Week 7) ───────────────────────────────────────
  {
    phase: 1,
    week: 7,
    day: 1,
    title: "Watch: How to install Tailwind 4 in Vite and Next.js (16:04)",
    topic_type: "video",
    estimated_minutes: 17,
  },
  {
    phase: 1,
    week: 7,
    day: 1,
    title: "Watch: Tailwind setup with CDN and NodeJS (27:07)",
    topic_type: "video",
    estimated_minutes: 28,
  },
  {
    phase: 1,
    week: 7,
    day: 1,
    title: "Hands-On: Setup Tailwind in 2 ways",
    topic_type: "setup",
    estimated_minutes: 60,
  },
  {
    phase: 1,
    week: 7,
    day: 2,
    title: "Watch: Full potential of Tailwind CSS (9:42)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 1,
    week: 7,
    day: 2,
    title: "Exercise: Style a Button with Tailwind CSS",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 7,
    day: 2,
    title: "Exercise: Center a Div Using Flexbox (Tailwind)",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 7,
    day: 3,
    title: "Watch: How to build responsive design in Tailwind (13:00)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 1,
    week: 7,
    day: 3,
    title: "Watch: Build any layout with Tailwind - Masterclass (34:27)",
    topic_type: "video",
    estimated_minutes: 35,
  },
  {
    phase: 1,
    week: 7,
    day: 3,
    title: "Exercise: Create a Basic Grid Layout (Tailwind)",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 1,
    week: 7,
    day: 3,
    title: "Exercise: Create a Responsive Flexbox Layout (Tailwind)",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 1,
    week: 7,
    day: 4,
    title: "Exercise: Apply Box Shadow to a Card Using Tailwind CSS",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 7,
    day: 4,
    title: "Exercise: Create a Donut Shape Using Tailwind CSS",
    topic_type: "exercise",
    estimated_minutes: 20,
  },
  {
    phase: 1,
    week: 7,
    day: 4,
    title: "Exercise: Add Blur Effect to an Image",
    topic_type: "exercise",
    estimated_minutes: 15,
  },
  {
    phase: 1,
    week: 7,
    day: 4,
    title: "Exercise: Create a Gradient Colored Button",
    topic_type: "exercise",
    estimated_minutes: 15,
  },
  {
    phase: 1,
    week: 7,
    day: 4,
    title: "Exercise: Create a Rotating Square Box",
    topic_type: "exercise",
    estimated_minutes: 15,
  },
  {
    phase: 1,
    week: 7,
    day: 5,
    title: "Watch: Production ready login screen project (20:56)",
    topic_type: "video",
    estimated_minutes: 21,
  },
  {
    phase: 1,
    week: 7,
    day: 5,
    title: "Project: Tailwind Login Screen",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 1,
    week: 7,
    day: 5,
    title: "Quiz: Tailwind Quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },

  // ── PHASE 2: JavaScript Foundations (Weeks 8–11) ──────────────────────────
  {
    phase: 2,
    week: 8,
    day: 1,
    title: "Watch: Javascript story - from console to v8 engine (11:45)",
    topic_type: "video",
    estimated_minutes: 12,
  },
  {
    phase: 2,
    week: 8,
    day: 1,
    title: "Watch: How javascript executes the code (12:39)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 2,
    week: 8,
    day: 2,
    title: "Watch: Datatypes, variables and constants (24:37)",
    topic_type: "video",
    estimated_minutes: 25,
  },
  {
    phase: 2,
    week: 8,
    day: 2,
    title: "Watch: Operations in javascript (20:39)",
    topic_type: "video",
    estimated_minutes: 21,
  },
  {
    phase: 2,
    week: 8,
    day: 2,
    title: "Exercise: Playing with Variables",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 2,
    week: 8,
    day: 2,
    title: "Exercise: Playing with Types",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 2,
    week: 8,
    day: 3,
    title: "Watch: Primitives in javascript (23:18)",
    topic_type: "video",
    estimated_minutes: 24,
  },
  {
    phase: 2,
    week: 8,
    day: 3,
    title: "Watch: Non Primitives in javascript (20:59)",
    topic_type: "video",
    estimated_minutes: 21,
  },
  {
    phase: 2,
    week: 8,
    day: 3,
    title: "Exercise: Primitive vs non-primitive challenges",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 8,
    day: 4,
    title: "Watch: Five challenges on conditions in javascript (19:04)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 2,
    week: 8,
    day: 4,
    title: "Exercise: Solve 10 condition problems",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 8,
    day: 5,
    title: "Quiz: JavaScript mini quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },
  {
    phase: 2,
    week: 8,
    day: 5,
    title: "Project: Build a simple calculator (conditionals + operations)",
    topic_type: "project",
    estimated_minutes: 60,
  },

  {
    phase: 2,
    week: 9,
    day: 1,
    title: "Watch: Facing ten challenges in Array and methods (35:07)",
    topic_type: "video",
    estimated_minutes: 36,
  },
  {
    phase: 2,
    week: 9,
    day: 1,
    title: "Exercise: Arrays and Methods",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 9,
    day: 2,
    title: "Watch: Introduction to loops in javascript (20:39)",
    topic_type: "video",
    estimated_minutes: 21,
  },
  {
    phase: 2,
    week: 9,
    day: 2,
    title: "Exercise: Loops — basic challenges (10 problems)",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 2,
    week: 9,
    day: 3,
    title: "Watch: Defeat 6 loop challenges (26:05)",
    topic_type: "video",
    estimated_minutes: 27,
  },
  {
    phase: 2,
    week: 9,
    day: 3,
    title: "Exercise: Solve nested loop problems",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 9,
    day: 4,
    title: "Watch: Ten loop challenges to learn all kinds of loops (47:37)",
    topic_type: "video",
    estimated_minutes: 48,
  },
  {
    phase: 2,
    week: 9,
    day: 4,
    title: "Exercise: Advanced loop challenges",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 9,
    day: 5,
    title: "Quiz: Quiz on Arrays",
    topic_type: "quiz",
    estimated_minutes: 20,
  },
  {
    phase: 2,
    week: 9,
    day: 5,
    title: "Quiz: Quiz on Loops",
    topic_type: "quiz",
    estimated_minutes: 20,
  },
  {
    phase: 2,
    week: 9,
    day: 5,
    title: "Project: Search & filter array data",
    topic_type: "project",
    estimated_minutes: 60,
  },

  {
    phase: 2,
    week: 10,
    day: 1,
    title: "Watch: Function, arrow function, THIS and context (26:16)",
    topic_type: "video",
    estimated_minutes: 27,
  },
  {
    phase: 2,
    week: 10,
    day: 1,
    title: "Exercise: Convert regular functions to arrow functions",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 10,
    day: 2,
    title: "Watch: Higher order function and nested functions (19:54)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 2,
    week: 10,
    day: 2,
    title: "Exercise: Higher-Order Functions and Arrow Functions",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 10,
    day: 2,
    title: "Exercise: Create map, filter, reduce implementations",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 10,
    day: 3,
    title: "Exercise: THIS binding quiz and problems",
    topic_type: "quiz",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 10,
    day: 4,
    title: "Exercise: Build event handlers with proper context",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 10,
    day: 5,
    title: "Project: Advanced Calculator with functions",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 2,
    week: 10,
    day: 5,
    title: "Review: All function concepts",
    topic_type: "review",
    estimated_minutes: 30,
  },

  {
    phase: 2,
    week: 11,
    day: 1,
    title: "Watch: A masterclass on prototypes in javascript (28:01)",
    topic_type: "video",
    estimated_minutes: 29,
  },
  {
    phase: 2,
    week: 11,
    day: 1,
    title: "Exercise: Prototypes in JavaScript — create prototype chains",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 11,
    day: 2,
    title: "Watch: Functional constructor and Errors (18:27)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 2,
    week: 11,
    day: 2,
    title: "Exercise: Build custom objects with constructors",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 11,
    day: 3,
    title: "Watch: Classes Objects and inheritance (19:54)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 2,
    week: 11,
    day: 3,
    title: "Exercise: Refactor constructors to ES6 classes",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 11,
    day: 4,
    title:
      "Watch: Encapsulation, Polymorphism, Abstraction, getters setters (30:17)",
    topic_type: "video",
    estimated_minutes: 31,
  },
  {
    phase: 2,
    week: 11,
    day: 4,
    title: "Exercise: Encapsulation and Polymorphism exercises",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 2,
    week: 11,
    day: 5,
    title: "Quiz: OOP Quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },
  {
    phase: 2,
    week: 11,
    day: 5,
    title: "Project: Bank Account System (OOP)",
    topic_type: "project",
    estimated_minutes: 120,
  },

  // ── PHASE 2 (Continued): DOM & Async (Weeks 12–13) ───────────────────────
  {
    phase: 2,
    week: 12,
    day: 1,
    title: "Watch: DOM and BOM basics in javascript (20:36)",
    topic_type: "video",
    estimated_minutes: 21,
  },
  {
    phase: 2,
    week: 12,
    day: 1,
    title: "Exercise: DOM selection and manipulation",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 12,
    day: 2,
    title: "Watch: Solving 5 challenges of DOM (35:15)",
    topic_type: "video",
    estimated_minutes: 36,
  },
  {
    phase: 2,
    week: 12,
    day: 2,
    title: "Exercise: DOM challenges 1–5",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 2,
    week: 12,
    day: 3,
    title: "Watch: DOM finale with 5 more challenges (33:46)",
    topic_type: "video",
    estimated_minutes: 34,
  },
  {
    phase: 2,
    week: 12,
    day: 3,
    title: "Exercise: DOM challenges 6–10",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 2,
    week: 12,
    day: 4,
    title: "Exercise: Progressive DOM challenges — advanced",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 2,
    week: 12,
    day: 5,
    title: "Project: Interactive To-Do App with DOM",
    topic_type: "project",
    estimated_minutes: 120,
  },

  {
    phase: 2,
    week: 13,
    day: 1,
    title: "Watch: Asynchronous Javascript with event loop (17:43)",
    topic_type: "video",
    estimated_minutes: 18,
  },
  {
    phase: 2,
    week: 13,
    day: 1,
    title: "Exercise: Understand async execution",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 2,
    week: 13,
    day: 2,
    title: "Watch: Promises and promise chaining (12:48)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 2,
    week: 13,
    day: 2,
    title: "Exercise: Build promise chains",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 13,
    day: 3,
    title: "Watch: Async-await and Promise all (15:11)",
    topic_type: "video",
    estimated_minutes: 16,
  },
  {
    phase: 2,
    week: 13,
    day: 3,
    title: "Exercise: Convert promises to async-await",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 13,
    day: 4,
    title: "Watch: Closures in javascript (4:37)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 2,
    week: 13,
    day: 4,
    title: "Watch: Iterator and generators (6:39)",
    topic_type: "video",
    estimated_minutes: 7,
  },
  {
    phase: 2,
    week: 13,
    day: 4,
    title: "Exercise: Advanced iteration patterns",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 2,
    week: 13,
    day: 5,
    title: "Project: API data fetcher with async-await",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 2,
    week: 13,
    day: 5,
    title: "Quiz: Advanced topics quiz",
    topic_type: "quiz",
    estimated_minutes: 30,
  },

  // ── PHASE 3: Hands-On JS Projects (Weeks 14–15) ──────────────────────────
  {
    phase: 3,
    week: 14,
    day: 1,
    title: "Watch: Demo of project 1 - Todo with local Storage (5:10)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 3,
    week: 14,
    day: 1,
    title: "Watch: Add a task in array (10:05)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 3,
    week: 14,
    day: 1,
    title: "Project: Build todo app — add/delete tasks",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 3,
    week: 14,
    day: 2,
    title: "Watch: Handling local storage and DOM event (9:34)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 3,
    week: 14,
    day: 2,
    title: "Watch: Event bubbling and CRUD operations (19:21)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 3,
    week: 14,
    day: 2,
    title: "Project: Full CRUD todo app with localStorage",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 3,
    week: 14,
    day: 3,
    title: "Watch: Demo of API handling project (4:57)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 3,
    week: 14,
    day: 3,
    title: "Watch: Handle any type of API in your code (36:37)",
    topic_type: "video",
    estimated_minutes: 37,
  },
  {
    phase: 3,
    week: 14,
    day: 3,
    title: "Project: Weather API app",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 3,
    week: 14,
    day: 4,
    title: "Watch: Demo of Project 3 Ecommerce app (1:50)",
    topic_type: "video",
    estimated_minutes: 2,
  },
  {
    phase: 3,
    week: 14,
    day: 4,
    title: "Watch: Building ecommerce cart page (27:10)",
    topic_type: "video",
    estimated_minutes: 28,
  },
  {
    phase: 3,
    week: 14,
    day: 4,
    title: "Project: E-commerce cart — product display + add to cart",
    topic_type: "project",
    estimated_minutes: 120,
  },
  {
    phase: 3,
    week: 14,
    day: 5,
    title: "Refactor and optimize e-commerce code",
    topic_type: "review",
    estimated_minutes: 60,
  },

  {
    phase: 3,
    week: 15,
    day: 1,
    title: "Watch: Demo of project 4 Expense Tracker (2:32)",
    topic_type: "video",
    estimated_minutes: 3,
  },
  {
    phase: 3,
    week: 15,
    day: 1,
    title:
      "Watch: Expense tracker with localstorage and event delegation (30:43)",
    topic_type: "video",
    estimated_minutes: 31,
  },
  {
    phase: 3,
    week: 15,
    day: 1,
    title: "Project: Expense tracker — add/delete/filter/total",
    topic_type: "project",
    estimated_minutes: 120,
  },
  {
    phase: 3,
    week: 15,
    day: 2,
    title: "Polish expense tracker UI and add advanced features",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 3,
    week: 15,
    day: 3,
    title: "Watch: Demo of project 5 - quiz application (3:35)",
    topic_type: "video",
    estimated_minutes: 4,
  },
  {
    phase: 3,
    week: 15,
    day: 3,
    title: "Watch: Building a complete quiz app (28:21)",
    topic_type: "video",
    estimated_minutes: 29,
  },
  {
    phase: 3,
    week: 15,
    day: 3,
    title: "Project: Quiz app — questions, score, timer, results",
    topic_type: "project",
    estimated_minutes: 120,
  },
  {
    phase: 3,
    week: 15,
    day: 4,
    title: "Add animations and admin quiz creation feature",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 3,
    week: 15,
    day: 5,
    title: "Push all 5 projects to GitHub with documentation",
    topic_type: "exercise",
    estimated_minutes: 60,
  },

  // ── PHASE 3B: Git & Version Control Deep Dive (Week 16) ───────────────────
  {
    phase: 3,
    week: 16,
    day: 1,
    title: "Watch: Introduction to GIT series (5:51)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 3,
    week: 16,
    day: 1,
    title: "Watch: Git init and hidden folder (17:30)",
    topic_type: "video",
    estimated_minutes: 18,
  },
  {
    phase: 3,
    week: 16,
    day: 1,
    title: "Watch: Git commits and logs (16:31)",
    topic_type: "video",
    estimated_minutes: 17,
  },
  {
    phase: 3,
    week: 16,
    day: 1,
    title: "Hands-On: Initialize repository from scratch",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 3,
    week: 16,
    day: 2,
    title: "Watch: Git internal working and configs (27:46)",
    topic_type: "video",
    estimated_minutes: 28,
  },
  {
    phase: 3,
    week: 16,
    day: 2,
    title: "Exercise: Understand .git folder structure",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 3,
    week: 16,
    day: 3,
    title: "Watch: Git merge and git conflicts (39:36)",
    topic_type: "video",
    estimated_minutes: 40,
  },
  {
    phase: 3,
    week: 16,
    day: 3,
    title: "Exercise: Create branches and handle conflicts",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 3,
    week: 16,
    day: 4,
    title: "Watch: Git Diff and stashing (28:22)",
    topic_type: "video",
    estimated_minutes: 29,
  },
  {
    phase: 3,
    week: 16,
    day: 4,
    title: "Watch: Git rebase is not that scary (21:43)",
    topic_type: "video",
    estimated_minutes: 22,
  },
  {
    phase: 3,
    week: 16,
    day: 4,
    title: "Exercise: Use diff, stash, and rebase",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 3,
    week: 16,
    day: 5,
    title: "Watch: Insight of pushing code to GitHub (40:57)",
    topic_type: "video",
    estimated_minutes: 41,
  },
  {
    phase: 3,
    week: 16,
    day: 5,
    title: "Watch: How to make Pull Request and Open Source (24:45)",
    topic_type: "video",
    estimated_minutes: 25,
  },
  {
    phase: 3,
    week: 16,
    day: 5,
    title: "Exercise: Push projects and create pull requests",
    topic_type: "exercise",
    estimated_minutes: 60,
  },

  // ── PHASE 4: Backend Foundations (Weeks 17–20) ────────────────────────────
  {
    phase: 4,
    week: 17,
    day: 1,
    title: "Watch: Backend - NodeJS LibUV and source code (18:55)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 4,
    week: 17,
    day: 2,
    title: "Watch: Handling files in Nodejs as Project (21:23)",
    topic_type: "video",
    estimated_minutes: 22,
  },
  {
    phase: 4,
    week: 17,
    day: 2,
    title: "Exercise: File read/write operations",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 17,
    day: 3,
    title: "Watch: Build your own Nginx server with NodeJS (first 15 mins)",
    topic_type: "video",
    estimated_minutes: 15,
  },
  {
    phase: 4,
    week: 17,
    day: 3,
    title: "Exercise: Create basic HTTP server",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 17,
    day: 4,
    title: "Watch: Event Driven Architecture - Build your own logger (25:34)",
    topic_type: "video",
    estimated_minutes: 26,
  },
  {
    phase: 4,
    week: 17,
    day: 4,
    title: "Exercise: Implement custom event emitter logger",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 17,
    day: 5,
    title: "Watch: Introduction to databases (10:40)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 4,
    week: 17,
    day: 5,
    title: "Watch: SQL vs NOSQL Databases (8:35)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 4,
    week: 17,
    day: 5,
    title: "Watch: A Quick tour of MongoDB (10:10)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 4,
    week: 17,
    day: 5,
    title: "Setup: MongoDB Atlas account",
    topic_type: "setup",
    estimated_minutes: 30,
  },

  {
    phase: 4,
    week: 18,
    day: 1,
    title: "Watch: Building a fresh Backend project (4:37)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 4,
    week: 18,
    day: 1,
    title: "Watch: Importance of Project requirement document (9:28)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 4,
    week: 18,
    day: 1,
    title: "Exercise: Create professional project structure",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 18,
    day: 2,
    title: "Watch: Preparing node project for backend (7:15)",
    topic_type: "video",
    estimated_minutes: 8,
  },
  {
    phase: 4,
    week: 18,
    day: 2,
    title: "Watch: Add prettier and git to the code base (9:23)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 4,
    week: 18,
    day: 3,
    title: "Watch: Auto restart your server (6:21)",
    topic_type: "video",
    estimated_minutes: 7,
  },
  {
    phase: 4,
    week: 18,
    day: 3,
    title: "Watch: Dot env files on backend (8:28)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 4,
    week: 18,
    day: 3,
    title: "Exercise: Setup nodemon and environment variables",
    topic_type: "setup",
    estimated_minutes: 30,
  },
  {
    phase: 4,
    week: 18,
    day: 4,
    title: "Watch: A professional project structure (8:17)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 4,
    week: 18,
    day: 4,
    title: "Watch: Setup of basic express server (9:42)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 4,
    week: 18,
    day: 4,
    title: "Watch: Separation of app with index (4:50)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 4,
    week: 18,
    day: 4,
    title:
      "Exercise: Create project structure with controllers, routes, models",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 18,
    day: 5,
    title: "Watch: Introducing postman for API testing (8:05)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 4,
    week: 18,
    day: 5,
    title: "Setup: Postman collection for testing",
    topic_type: "setup",
    estimated_minutes: 30,
  },

  {
    phase: 4,
    week: 19,
    day: 1,
    title: "Watch: Express configuration and CORS (12:48)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 4,
    week: 19,
    day: 1,
    title: "Watch: Standard ApiResponse and API errors (10:32)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 4,
    week: 19,
    day: 2,
    title: "Watch: How to connect with mongoDB (7:07)",
    topic_type: "video",
    estimated_minutes: 8,
  },
  {
    phase: 4,
    week: 19,
    day: 2,
    title: "Watch: A guide on mongodb Atlas connection (10:04)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 4,
    week: 19,
    day: 2,
    title: "Exercise: Connect to MongoDB Atlas",
    topic_type: "setup",
    estimated_minutes: 30,
  },
  {
    phase: 4,
    week: 19,
    day: 3,
    title: "Watch: Write a healthcheck controller and routes (13:35)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 4,
    week: 19,
    day: 3,
    title: "Watch: Catch errors better with async Handlers (10:25)",
    topic_type: "video",
    estimated_minutes: 11,
  },
  {
    phase: 4,
    week: 19,
    day: 4,
    title: "Watch: Learn to write user schema in mongoose (18:33)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 4,
    week: 19,
    day: 4,
    title: "Watch: Hash the password with pre hooks (8:10)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 4,
    week: 19,
    day: 4,
    title: "Exercise: Create user schema with password hashing",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 19,
    day: 5,
    title: "Watch: What are JWT Tokens (7:34)",
    topic_type: "video",
    estimated_minutes: 8,
  },
  {
    phase: 4,
    week: 19,
    day: 5,
    title: "Watch: Theory behind Access token and refresh token (9:38)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 4,
    week: 19,
    day: 5,
    title: "Watch: Code for access and refresh token (16:29)",
    topic_type: "video",
    estimated_minutes: 17,
  },
  {
    phase: 4,
    week: 19,
    day: 5,
    title: "Exercise: Implement JWT token generation",
    topic_type: "exercise",
    estimated_minutes: 60,
  },

  {
    phase: 4,
    week: 20,
    day: 1,
    title: "Watch: How to register a user (25:38)",
    topic_type: "video",
    estimated_minutes: 26,
  },
  {
    phase: 4,
    week: 20,
    day: 1,
    title: "Watch: Routers for registering a user (4:10)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 4,
    week: 20,
    day: 1,
    title: "Exercise: Build registration endpoint",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 4,
    week: 20,
    day: 2,
    title: "Watch: Test register route with postman (6:25)",
    topic_type: "video",
    estimated_minutes: 7,
  },
  {
    phase: 4,
    week: 20,
    day: 2,
    title: "Watch: Writing custom validations (21:24)",
    topic_type: "video",
    estimated_minutes: 22,
  },
  {
    phase: 4,
    week: 20,
    day: 3,
    title: "Watch: Login user with tokens and cookie data (15:34)",
    topic_type: "video",
    estimated_minutes: 16,
  },
  {
    phase: 4,
    week: 20,
    day: 3,
    title: "Watch: Login validation and testing (5:05)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 4,
    week: 20,
    day: 3,
    title: "Exercise: Build login endpoint with tokens",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 20,
    day: 4,
    title: "Watch: Write auth middleware (15:11)",
    topic_type: "video",
    estimated_minutes: 16,
  },
  {
    phase: 4,
    week: 20,
    day: 4,
    title: "Watch: How to securely logout a user (9:23)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 4,
    week: 20,
    day: 4,
    title: "Exercise: Create protected routes with middleware",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 4,
    week: 20,
    day: 5,
    title: "Watch: Refresh Access token and resend verification email (25:43)",
    topic_type: "video",
    estimated_minutes: 26,
  },
  {
    phase: 4,
    week: 20,
    day: 5,
    title: "Watch: All password related controllers (18:45)",
    topic_type: "video",
    estimated_minutes: 19,
  },
  {
    phase: 4,
    week: 20,
    day: 5,
    title: "Exercise: Build refresh token and password reset features",
    topic_type: "exercise",
    estimated_minutes: 120,
  },

  // ── PHASE 5: Intermediate Backend (Weeks 21–22) ───────────────────────────
  {
    phase: 5,
    week: 21,
    day: 1,
    title: "Watch: Schema for projects, tasks and notes (22:20)",
    topic_type: "video",
    estimated_minutes: 23,
  },
  {
    phase: 5,
    week: 21,
    day: 1,
    title: "Watch: Planning project controllers (7:27)",
    topic_type: "video",
    estimated_minutes: 8,
  },
  {
    phase: 5,
    week: 21,
    day: 1,
    title: "Exercise: Design project, task, note schemas",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 5,
    week: 21,
    day: 2,
    title: "Watch: Create, update and delete projects (12:40)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 5,
    week: 21,
    day: 2,
    title: "Exercise: Implement project CRUD",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 5,
    week: 21,
    day: 3,
    title: "Watch: Write your 1st aggregation pipeline (16:30)",
    topic_type: "video",
    estimated_minutes: 17,
  },
  {
    phase: 5,
    week: 21,
    day: 3,
    title: "Watch: Writing all controllers for project model (25:05)",
    topic_type: "video",
    estimated_minutes: 26,
  },
  {
    phase: 5,
    week: 21,
    day: 3,
    title: "Exercise: Build complex queries with aggregation",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 5,
    week: 21,
    day: 4,
    title: "Watch: Role base permission implementation (12:52)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 5,
    week: 21,
    day: 4,
    title: "Watch: Writing project validators (5:12)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 5,
    week: 21,
    day: 4,
    title: "Exercise: Implement authorization and validation",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 5,
    week: 21,
    day: 5,
    title: "Watch: Handling project routes and permissions (16:51)",
    topic_type: "video",
    estimated_minutes: 17,
  },
  {
    phase: 5,
    week: 21,
    day: 5,
    title: "Watch: Upload file with multer in backend (8:23)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 5,
    week: 21,
    day: 5,
    title: "Exercise: File upload functionality",
    topic_type: "exercise",
    estimated_minutes: 60,
  },

  {
    phase: 5,
    week: 22,
    day: 1,
    title: "Watch: MongoDB aggregation setup (19:58)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 5,
    week: 22,
    day: 1,
    title: "Exercise: Build basic aggregation pipelines",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 5,
    week: 22,
    day: 2,
    title: "Watch: Grouping in MongoDB (24:50)",
    topic_type: "video",
    estimated_minutes: 25,
  },
  {
    phase: 5,
    week: 22,
    day: 2,
    title: "Watch: Group sum and more (12:56)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 5,
    week: 22,
    day: 2,
    title: "Exercise: Create grouping queries",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 5,
    week: 22,
    day: 3,
    title: "Watch: Dealing with arrays in aggregation (13:49)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 5,
    week: 22,
    day: 3,
    title: "Watch: Match and project pipeline (15:51)",
    topic_type: "video",
    estimated_minutes: 16,
  },
  {
    phase: 5,
    week: 22,
    day: 3,
    title: "Exercise: Multi-stage aggregation pipelines",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 5,
    week: 22,
    day: 4,
    title: "Watch: Match all operators of aggregation (21:01)",
    topic_type: "video",
    estimated_minutes: 22,
  },
  {
    phase: 5,
    week: 22,
    day: 4,
    title: "Watch: Lookup in MongoDB aggregation (9:46)",
    topic_type: "video",
    estimated_minutes: 10,
  },
  {
    phase: 5,
    week: 22,
    day: 4,
    title: "Exercise: Perform joins between collections with Lookup",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 5,
    week: 22,
    day: 5,
    title: "Exercise: Build complex reporting queries",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 5,
    week: 22,
    day: 5,
    title: "Exercise: Optimize database queries",
    topic_type: "exercise",
    estimated_minutes: 60,
  },

  // ── PHASE 6: Frontend with React (Weeks 23–26) ────────────────────────────
  {
    phase: 6,
    week: 23,
    day: 1,
    title: "Watch: React Roadmap (19:17)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 6,
    week: 23,
    day: 1,
    title: "Watch: Create react projects (22:32)",
    topic_type: "video",
    estimated_minutes: 23,
  },
  {
    phase: 6,
    week: 23,
    day: 1,
    title: "Exercise: Create React project with Vite",
    topic_type: "setup",
    estimated_minutes: 30,
  },
  {
    phase: 6,
    week: 23,
    day: 2,
    title: "Watch: Understand the react flow and structure (26:38)",
    topic_type: "video",
    estimated_minutes: 27,
  },
  {
    phase: 6,
    week: 23,
    day: 2,
    title: "Watch: Create your own react library and JSX (31:29)",
    topic_type: "video",
    estimated_minutes: 32,
  },
  {
    phase: 6,
    week: 23,
    day: 2,
    title: "Exercise: Build custom components",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 6,
    week: 23,
    day: 3,
    title: "Watch: Why you need hooks and project (19:27)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 6,
    week: 23,
    day: 3,
    title: "Watch: Virtual DOM, Fibre and reconciliation (13:43)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 6,
    week: 23,
    day: 4,
    title: "Watch: Tailwind and Props in reactjs (26:38)",
    topic_type: "video",
    estimated_minutes: 27,
  },
  {
    phase: 6,
    week: 23,
    day: 4,
    title: "Exercise: Build prop-based components",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 6,
    week: 23,
    day: 5,
    title: "Watch: Building a react project bgChanger (17:46)",
    topic_type: "video",
    estimated_minutes: 18,
  },
  {
    phase: 6,
    week: 23,
    day: 5,
    title: "Project: BG Changer app",
    topic_type: "project",
    estimated_minutes: 60,
  },

  {
    phase: 6,
    week: 24,
    day: 1,
    title: "Watch: useEffect, useRef and useCallback with project (40:17)",
    topic_type: "video",
    estimated_minutes: 41,
  },
  {
    phase: 6,
    week: 24,
    day: 1,
    title: "Exercise: Build project using hooks",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 6,
    week: 24,
    day: 2,
    title: "Watch: Custom hooks in react - Currency Project (52:31)",
    topic_type: "video",
    estimated_minutes: 53,
  },
  {
    phase: 6,
    week: 24,
    day: 2,
    title: "Project: Currency converter with custom hooks",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 6,
    week: 24,
    day: 3,
    title: "Exercise: Optimize re-renders with useCallback and useMemo",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 6,
    week: 24,
    day: 4,
    title: "Exercise: Lift state up patterns and prop drilling solutions",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 6,
    week: 24,
    day: 5,
    title: "Project: Multi-component app",
    topic_type: "project",
    estimated_minutes: 90,
  },

  {
    phase: 6,
    week: 25,
    day: 1,
    title: "Watch: React router crash course (55:53)",
    topic_type: "video",
    estimated_minutes: 56,
  },
  {
    phase: 6,
    week: 25,
    day: 1,
    title: "Exercise: Setup routing in app",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 6,
    week: 25,
    day: 2,
    title: "Exercise: Route parameters, dynamic routes, nested layouts",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 6,
    week: 25,
    day: 3,
    title: "Watch: Context API in react - get the concept (28:59)",
    topic_type: "video",
    estimated_minutes: 29,
  },
  {
    phase: 6,
    week: 25,
    day: 3,
    title: "Exercise: Create context providers",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 6,
    week: 25,
    day: 4,
    title: "Watch: Build a dark mode light mode in reactjs (29:19)",
    topic_type: "video",
    estimated_minutes: 30,
  },
  {
    phase: 6,
    week: 25,
    day: 4,
    title: "Watch: Context API with local Storage (1:08:18)",
    topic_type: "video",
    estimated_minutes: 69,
  },
  {
    phase: 6,
    week: 25,
    day: 4,
    title: "Project: Theme switching with persistence",
    topic_type: "project",
    estimated_minutes: 60,
  },
  {
    phase: 6,
    week: 25,
    day: 5,
    title: "Project: Complex multi-feature app with routing and context",
    topic_type: "project",
    estimated_minutes: 90,
  },

  {
    phase: 6,
    week: 26,
    day: 1,
    title: "Project: Movie App — fetch API, display, filter, favorites (Day 1)",
    topic_type: "project",
    estimated_minutes: 180,
  },
  {
    phase: 6,
    week: 26,
    day: 2,
    title: "Project: Movie App — complete and polish (Day 2)",
    topic_type: "project",
    estimated_minutes: 180,
  },
  {
    phase: 6,
    week: 26,
    day: 3,
    title: "Project: E-commerce Frontend — product listing, cart (Day 1)",
    topic_type: "project",
    estimated_minutes: 180,
  },
  {
    phase: 6,
    week: 26,
    day: 4,
    title: "Project: E-commerce Frontend — checkout flow (Day 2)",
    topic_type: "project",
    estimated_minutes: 180,
  },
  {
    phase: 6,
    week: 26,
    day: 5,
    title: "Review: Code review and performance optimization",
    topic_type: "review",
    estimated_minutes: 90,
  },

  // ── PHASE 7: Full-Stack with Next.js (Weeks 27–28) ────────────────────────
  {
    phase: 7,
    week: 27,
    day: 1,
    title: "Watch: Next.js introduction, setup, app router vs pages router",
    topic_type: "video",
    estimated_minutes: 30,
  },
  {
    phase: 7,
    week: 27,
    day: 1,
    title: "Exercise: Create Next.js project",
    topic_type: "setup",
    estimated_minutes: 30,
  },
  {
    phase: 7,
    week: 27,
    day: 2,
    title: "Watch: Nextjs auth full stack (1:04:10)",
    topic_type: "video",
    estimated_minutes: 65,
  },
  {
    phase: 7,
    week: 27,
    day: 2,
    title: "Exercise: Implement auth system",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 7,
    week: 27,
    day: 3,
    title: "Watch: Signup and login (1:01:37)",
    topic_type: "video",
    estimated_minutes: 62,
  },
  {
    phase: 7,
    week: 27,
    day: 3,
    title: "Exercise: Build auth pages",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 7,
    week: 27,
    day: 4,
    title: "Watch: Middleware in nextjs (41:38)",
    topic_type: "video",
    estimated_minutes: 42,
  },
  {
    phase: 7,
    week: 27,
    day: 4,
    title: "Exercise: Implement route protection",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 7,
    week: 27,
    day: 5,
    title: "Watch: User verification email in Nextjs (56:03)",
    topic_type: "video",
    estimated_minutes: 57,
  },
  {
    phase: 7,
    week: 27,
    day: 5,
    title: "Exercise: Complete email verification flow",
    topic_type: "exercise",
    estimated_minutes: 60,
  },

  {
    phase: 7,
    week: 28,
    day: 1,
    title: "Watch: Building a stack overflow clone with Next.js (6:23)",
    topic_type: "video",
    estimated_minutes: 7,
  },
  {
    phase: 7,
    week: 28,
    day: 1,
    title: "Watch: Initialize Prisma and Connect to MongoDB (13:28)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 7,
    week: 28,
    day: 1,
    title: "Exercise: Database schema design",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 7,
    week: 28,
    day: 2,
    title: "Watch: Landing page design (19:11)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 7,
    week: 28,
    day: 2,
    title: "Watch: Building a Dashboard UI (50:47)",
    topic_type: "video",
    estimated_minutes: 51,
  },
  {
    phase: 7,
    week: 28,
    day: 2,
    title: "Exercise: UI components creation",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 7,
    week: 28,
    day: 3,
    title: "Watch: Playground Functionality 1 (27:46)",
    topic_type: "video",
    estimated_minutes: 28,
  },
  {
    phase: 7,
    week: 28,
    day: 3,
    title: "Watch: File explorer part 1 (56:41)",
    topic_type: "video",
    estimated_minutes: 57,
  },
  {
    phase: 7,
    week: 28,
    day: 4,
    title: "Watch: Playground Functionality 2 (5:33)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 7,
    week: 28,
    day: 4,
    title: "Watch: Monaco editor part 1 (30:12)",
    topic_type: "video",
    estimated_minutes: 31,
  },
  {
    phase: 7,
    week: 28,
    day: 4,
    title: "Exercise: Integrate Monaco code editor",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 7,
    week: 28,
    day: 5,
    title: "Watch: NextJS Deployment to Vercel (13:23)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 7,
    week: 28,
    day: 5,
    title: "Project: Deploy app to Vercel",
    topic_type: "project",
    estimated_minutes: 60,
  },

  // ── PHASE 8: Advanced & AI Integration (Weeks 29–30) ─────────────────────
  {
    phase: 8,
    week: 29,
    day: 1,
    title: "Watch: A complete backend project on Fastify (11:57)",
    topic_type: "video",
    estimated_minutes: 12,
  },
  {
    phase: 8,
    week: 29,
    day: 1,
    title: "Watch: Fastify server and plugin ecosystem (22:55)",
    topic_type: "video",
    estimated_minutes: 23,
  },
  {
    phase: 8,
    week: 29,
    day: 1,
    title: "Exercise: Create Fastify server",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 8,
    week: 29,
    day: 2,
    title: "Watch: Building your own plugins in fastify (17:34)",
    topic_type: "video",
    estimated_minutes: 18,
  },
  {
    phase: 8,
    week: 29,
    day: 2,
    title: "Exercise: Build reusable plugins",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 8,
    week: 29,
    day: 3,
    title: "Watch: User authentication and fastify jwt plugins (53:52)",
    topic_type: "video",
    estimated_minutes: 54,
  },
  {
    phase: 8,
    week: 29,
    day: 3,
    title: "Exercise: Implement JWT in Fastify",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 8,
    week: 29,
    day: 4,
    title: "Watch: Learn about streams in nodejs and Fastify (46:41)",
    topic_type: "video",
    estimated_minutes: 47,
  },
  {
    phase: 8,
    week: 29,
    day: 4,
    title: "Exercise: Implement streaming features",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 8,
    week: 29,
    day: 5,
    title: "Review: Security best practices and production error handling",
    topic_type: "review",
    estimated_minutes: 90,
  },

  {
    phase: 8,
    week: 30,
    day: 1,
    title: "Watch: Ollama setup 1 (4:03)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 8,
    week: 30,
    day: 1,
    title: "Watch: Ollama setup 2 (4:07)",
    topic_type: "video",
    estimated_minutes: 5,
  },
  {
    phase: 8,
    week: 30,
    day: 1,
    title: "Setup: Install and configure Ollama locally",
    topic_type: "setup",
    estimated_minutes: 60,
  },
  {
    phase: 8,
    week: 30,
    day: 2,
    title: "Watch: AI Module Part 1 - part a (39:02)",
    topic_type: "video",
    estimated_minutes: 40,
  },
  {
    phase: 8,
    week: 30,
    day: 2,
    title: "Watch: AI Module Part 1 - part b (19:09)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 8,
    week: 30,
    day: 2,
    title: "Exercise: Build code completion API",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 8,
    week: 30,
    day: 3,
    title: "Watch: AI Module Part 1 - part c (25:19)",
    topic_type: "video",
    estimated_minutes: 26,
  },
  {
    phase: 8,
    week: 30,
    day: 3,
    title: "Exercise: Implement inline completion in Monaco editor",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 8,
    week: 30,
    day: 4,
    title: "Watch: AI Module Part 2 - part a (19:10)",
    topic_type: "video",
    estimated_minutes: 20,
  },
  {
    phase: 8,
    week: 30,
    day: 4,
    title: "Watch: AI Module Part 2 - part b (24:35)",
    topic_type: "video",
    estimated_minutes: 25,
  },
  {
    phase: 8,
    week: 30,
    day: 4,
    title: "Exercise: Build AI chat feature",
    topic_type: "exercise",
    estimated_minutes: 90,
  },
  {
    phase: 8,
    week: 30,
    day: 5,
    title: "Project: Integrate all AI features and deploy full AI IDE",
    topic_type: "project",
    estimated_minutes: 180,
  },

  // ── PHASE 9: Deployment & DevOps (Weeks 31–32) ────────────────────────────
  {
    phase: 9,
    week: 31,
    day: 1,
    title: "Watch: Foundation of containers (7:22)",
    topic_type: "video",
    estimated_minutes: 8,
  },
  {
    phase: 9,
    week: 31,
    day: 1,
    title: "Watch: Containers Vs Virtual Machine (8:19)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 9,
    week: 31,
    day: 2,
    title: "Watch: Run your first container (8:27)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 9,
    week: 31,
    day: 2,
    title: "Watch: Docker cli commands (14:57)",
    topic_type: "video",
    estimated_minutes: 15,
  },
  {
    phase: 9,
    week: 31,
    day: 2,
    title: "Exercise: Run and manage containers",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 9,
    week: 31,
    day: 3,
    title: "Watch: Key Docker Concepts (5:59)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 9,
    week: 31,
    day: 3,
    title: "Watch: Writing a Dockerfile (32:31)",
    topic_type: "video",
    estimated_minutes: 33,
  },
  {
    phase: 9,
    week: 31,
    day: 3,
    title: "Exercise: Create custom Docker images",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 9,
    week: 31,
    day: 4,
    title: "Watch: Containerizing a simple Node.js app (13:42)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 9,
    week: 31,
    day: 4,
    title: "Watch: Docker multi-stage build (8:50)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 9,
    week: 31,
    day: 4,
    title: "Project: Containerize full-stack app",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 9,
    week: 31,
    day: 5,
    title: "Watch: Managing containers (13:41)",
    topic_type: "video",
    estimated_minutes: 14,
  },
  {
    phase: 9,
    week: 31,
    day: 5,
    title: "Exercise: Multi-container orchestration with Docker Compose",
    topic_type: "exercise",
    estimated_minutes: 60,
  },

  {
    phase: 9,
    week: 32,
    day: 1,
    title: "Watch: How to setup VPC for deployment (31:52)",
    topic_type: "video",
    estimated_minutes: 32,
  },
  {
    phase: 9,
    week: 32,
    day: 1,
    title: "Watch: How to configure nginx on VPS (17:01)",
    topic_type: "video",
    estimated_minutes: 18,
  },
  {
    phase: 9,
    week: 32,
    day: 1,
    title: "Exercise: Setup VPS and Nginx",
    topic_type: "setup",
    estimated_minutes: 90,
  },
  {
    phase: 9,
    week: 32,
    day: 2,
    title: "Watch: How to add rate limiting in nginx (12:04)",
    topic_type: "video",
    estimated_minutes: 13,
  },
  {
    phase: 9,
    week: 32,
    day: 2,
    title: "Watch: How to install SSL on nginx (8:26)",
    topic_type: "video",
    estimated_minutes: 9,
  },
  {
    phase: 9,
    week: 32,
    day: 2,
    title: "Exercise: Configure rate limiting and SSL/HTTPS",
    topic_type: "exercise",
    estimated_minutes: 60,
  },
  {
    phase: 9,
    week: 32,
    day: 3,
    title: "Watch: How to configure domain to a VPS (5:27)",
    topic_type: "video",
    estimated_minutes: 6,
  },
  {
    phase: 9,
    week: 32,
    day: 3,
    title: "Exercise: Point domain to VPS",
    topic_type: "exercise",
    estimated_minutes: 30,
  },
  {
    phase: 9,
    week: 32,
    day: 4,
    title: "Watch: How to deploy node api with nginx (16:32)",
    topic_type: "video",
    estimated_minutes: 17,
  },
  {
    phase: 9,
    week: 32,
    day: 4,
    title: "Project: Deploy Node.js API to VPS",
    topic_type: "project",
    estimated_minutes: 90,
  },
  {
    phase: 9,
    week: 32,
    day: 5,
    title: "Watch: Your own Vercel on VPS - Coolify (14:06)",
    topic_type: "video",
    estimated_minutes: 15,
  },
  {
    phase: 9,
    week: 32,
    day: 5,
    title: "Setup: Production monitoring and logging",
    topic_type: "setup",
    estimated_minutes: 60,
  },
];

async function seed() {
  console.log(`Seeding ${curriculum.length} curriculum items...`);

  // Clear existing data
  await supabase
    .from("gg_curriculum")
    .delete()
    .neq("id", "00000000-0000-0000-0000-000000000000");

  const rows = curriculum.map((item, idx) => ({
    phase: item.phase,
    week: item.week,
    day: item.day ?? null,
    title: item.title,
    topic_type: item.topic_type,
    order_index: idx,
    estimated_minutes: item.estimated_minutes ?? null,
  }));

  // Insert in batches of 100
  const batchSize = 100;
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const { error } = await supabase.from("gg_curriculum").insert(batch);
    if (error) {
      console.error(`Error inserting batch ${i / batchSize + 1}:`, error);
      process.exit(1);
    }
    console.log(
      `  Inserted batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(rows.length / batchSize)}`,
    );
  }

  console.log("✅ Curriculum seeded successfully!");
}

seed().catch(console.error);
